version: '3'
services:
  database:
    image: postgres:14-alpine
    container_name: "database"
    environment:
      - POSTGRES_DB=workplace_reservation
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  server:
    build:
      context: ./server
    container_name: "server"
    ports:
      - "8080:8080"
    depends_on:
      - database
  client:
    build:
      context: ./webapp
    container_name: "client"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://go-server:8080/api
    depends_on:
      - server
