version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
  client:
    build:
      context: ./webapp
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://go-server:8080/api
    depends_on:
      - server
