// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/reservations/reoccurring": {
            "post": {
                "tags": [
                    "reservation"
                ],
                "summary": "Adds a reoccurring reservation",
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "tags": [
                    "accounts"
                ],
                "summary": "Get user information by id if logged in",
                "responses": {}
            },
            "post": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create a new account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TODO",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "TODO",
                        "name": "password",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "TODO",
                        "name": "username",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "TODO",
                        "name": "firstName",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "TODO",
                        "name": "lastName",
                        "in": "path"
                    }
                ],
                "responses": {}
            }
        },
        "/users/edit": {
            "patch": {
                "tags": [
                    "accounts"
                ],
                "responses": {}
            }
        },
        "/users/login": {
            "post": {
                "tags": [
                    "accounts"
                ],
                "summary": "Login with existing user",
                "responses": {}
            }
        },
        "/workplace/create": {
            "post": {
                "tags": [
                    "workplaces"
                ],
                "summary": "Creating a new workplace",
                "responses": {}
            }
        },
        "/workplace/reservation": {
            "delete": {
                "tags": [
                    "reservation"
                ],
                "summary": "Deletes a reservation",
                "responses": {}
            }
        },
        "/workplace/reservations": {
            "get": {
                "tags": [
                    "reservation"
                ],
                "summary": "Returns all reservations of the specified timespan",
                "responses": {}
            }
        },
        "/workplace/reserve": {
            "post": {
                "tags": [
                    "reservation"
                ],
                "summary": "Reserving a workplace for the requested timespan",
                "responses": {}
            }
        },
        "/workplaces": {
            "get": {
                "tags": [
                    "workplaces"
                ],
                "summary": "Returns all workplaces with reservations in the requested timespan and the linked office",
                "responses": {}
            }
        },
        "/workplaces/names": {
            "get": {
                "tags": [
                    "workplaces"
                ],
                "summary": "Returns the names of all workplaces",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Workplace Reservation API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
